meta_product_name: "Climbark"
meta_title: "Climbark | Navigate through routes and log your climbs more efficiently!"
meta_description: "Scrap your book and navigate through routes and log your climbs more efficiently with Climbark."
meta_image: "cover.jpg" # should exist in `app/assets/images/`
twitter_account: "@climbark"   # required for Twitter Cards
